routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//injeccion de dependencia
Route::bind('producto',function($url){
  return App\Producto::where('url',$url)->first();
});

Route::bind('categoria',function($categoria){
  return App\Categoria::find($categoria);
});

Route::bind('usuario',function($usuario){
  return App\User::find($usuario);
});

Route::bind('orden',function($orden){
  return App\Orden::find($orden);
});

Route::get('/', [
  'as'=>'store',
  'uses'=>'StoreController@index'
  ]);

  Route::get('producto/{url}', [
    'as'=>'producto-detalle',
    'uses'=>'StoreController@show'
    ]);
//Carrito
 Route::get('carrito/mostrar',[
  'as' => 'mostrar-carrito',
  'uses'=>'CartController@show'
  ]);

  Route::get('carrito/agregar/{producto}',[
  'as'=> 'agregar-carrito',
  'uses' => 'CartController@add'
]);

  Route::get('carrito/eliminar/{producto}',[
  'as'=> 'eliminar-carrito',
  'uses' => 'CartController@delete'
  ]);

  Route::get('carrito/trash',[
  'as'=> 'carrito-trash',
  'uses' => 'CartController@trash'
  ]);

  Route::get('carrito/actualizar/{producto}/{cantidad?}',[
  'as'=> 'actualizar-carrito',
  'uses' => 'CartController@update'
  ]);

  Route::get('detalle-orden',[
    'middleware'=>'auth',
    'as' => 'detalle-orden',
    'uses'=> 'CartController@orderDetail'
  ]);

//Authentication
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@authenticate');
Route::get('logout', 'Auth\LoginController@logout', function () {
    return abort(404);
})->name('logout');

Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Route::get('/home', 'HomeController@index')->name('home');

//paypal
//Enviamos nuestro pedido
Route::get('payment',array(
  'as'=>'payment',
  'uses'=>'PaypalController@postPayment'
));
//Paypa redirecciona a esta ruta
Route::get('payment/status',array(
  'as'=>'payment.status',
  'uses'=>'PaypalController@getPaymentStatus'
));

//admin
Route::group(['namespace' => 'Admin', 'middleware' => ['admin'], 'prefix' => 'admin'], function()
{

  Route::get('home', function(){
    return view('admin.home');
  });

  Route::resource('categoria','CategoriaController');
  Route::resource('producto','ProductoController');
  Route::resource('usuario','UsuarioController');

  Route::get('ordenes',[
    'as' => 'admin.orden.index',
    'uses' => 'OrdenController@index'
  ]);

  Route::post('orden/get-items',[
    'as' => 'admin.orden.getItems',
    'uses' => 'OrdenController@getItems'
  ]);

  Route::post('orden/{id}',[
    'as' => 'admin.orden.destroy',
    'uses' => 'OrdenController@destroy'
  ]);
});

resources/views/admin/partials/errores.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/admin/partials/footer.blade.php
<footer class="bg-dark container-fluid text-center">
  <h3>Desarrollado por César Gutiérrez </h3>
</footer>

resources/views/admin/partials/message.blade.php
<div class="alert alert-success alert-dismissible text-center mt-0 mb-0" role="alert">
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
  <span aria-hidden="true">&times;</span>
</button>
<h2><strong><i class="fa fa-info-circle"></i></strong> {{ \Session::get('message') }}</h2>
</div>

resources/views/admin/partials/modal-detalle-pedido.blade.php
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Detalle del Pedido: </h4>
      </div>
      <div class="modal-body">

        <div class="table-responsive">
          <table class="table table-stripped table-bordered table-hover" id="table-detalle-pedido">
            <thead>
              <tr>
                <th>Imagen</th>
                <th>Producto</th>
                <th>Precio</th>
                <th>Cantidad</th>
                <th>Subtotal</th>
              </tr>
            </thead>
            <tbody>

            </tbody>
          </table>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

resources/views/admin/partials/nav.blade.php
<nav class="navbar navbar-expand-lg navbar-default navbar-light bg-light">
  <a href="{{'home'}}">
    <img src="{{ asset('imagenes/logo.png') }}"  width="180" height="45" class="d-inline-block align-top">
  </a>
  <div class="dashboard ml-5">
    <h3> <i class="fa fa-dashboard"></i> Dashboard</h3>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="nav navbar-nav ml-auto">
      <li ><a href="{{route('categoria.index')}}"><h5>Categorias</h5></a> </li>
      <li ><a href="{{route('producto.index')}}"><h5>Productos</h5></a></li>
      <li ><a href="{{'ordenes'}}"><h5>Pedidos</h5></a></li>
      <li ><a href="{{route('usuario.index')}}"><h5>Usuarios</h5></a></li>

    <div class="btn-group">
      <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        {{Auth::user()->usuario}}
      </button>
      <div class="dropdown-menu dropdown-menu-right">
        @if(Auth::user()->rol =='administrador')
          <a class="dropdown-item" href="{{url('')}}"  name="button">
            Ver la página
          </a>
        @endif
        <a class="dropdown-item" href="{{route('logout')}}">Cerrar Sesión</a>
      </div>
    </div>
    </ul>
  </div>

</nav>